// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg3_X-qha7_4eMc4fGQR6rDQUmNlhefsU',
    appId: '1:576276692127:web:d6a007ec3919aed24c36aa',
    messagingSenderId: '576276692127',
    projectId: 'app-bh-40bdd',
    authDomain: 'app-bh-40bdd.firebaseapp.com',
    storageBucket: 'app-bh-40bdd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOaS-BA3ATQKa7aCB1X9Hvt3HP4Hdb4zw',
    appId: '1:576276692127:android:0f9c48dc0d9413e74c36aa',
    messagingSenderId: '576276692127',
    projectId: 'app-bh-40bdd',
    storageBucket: 'app-bh-40bdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMnNnQ71Y7en5vb_dA9sUKSklOajby9vg',
    appId: '1:576276692127:ios:cf589c9f5b483e634c36aa',
    messagingSenderId: '576276692127',
    projectId: 'app-bh-40bdd',
    storageBucket: 'app-bh-40bdd.firebasestorage.app',
    iosBundleId: 'com.example.appClient2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMnNnQ71Y7en5vb_dA9sUKSklOajby9vg',
    appId: '1:576276692127:ios:cf589c9f5b483e634c36aa',
    messagingSenderId: '576276692127',
    projectId: 'app-bh-40bdd',
    storageBucket: 'app-bh-40bdd.firebasestorage.app',
    iosBundleId: 'com.example.appClient2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg3_X-qha7_4eMc4fGQR6rDQUmNlhefsU',
    appId: '1:576276692127:web:450f7176758e85ca4c36aa',
    messagingSenderId: '576276692127',
    projectId: 'app-bh-40bdd',
    authDomain: 'app-bh-40bdd.firebaseapp.com',
    storageBucket: 'app-bh-40bdd.firebasestorage.app',
  );

}